openapi: 3.0.3
info:
  title: 'Book Reservation Portal'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
tags:
  -
    name: Admin
    description: ''
  -
    name: Auth
    description: "\nAPI endpoints for managing auth"
  -
    name: User
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
paths:
  '/api/admin/books/{book_id}/bookCopies':
    get:
      summary: 'All book copies'
      operationId: allBookCopies
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: uuid
                    title: Title
                    visible: true
                    branch_id: 'Branch ID'
                    status: available
                    condition: good
                    special: true
                    created_at: date
                    updated_at: date
      tags:
        - Admin
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                q:
                  type: string
                  description: ''
                  example: porro
                  nullable: true
                per_page:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 40
                  nullable: true
                page:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 68
                  nullable: true
    post:
      summary: 'Store new book copy'
      operationId: storeNewBookCopy
      description: ''
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: uuid
                  title: Title
                  visible: true
                  branch_id: 'Branch ID'
                  status: available
                  condition: good
                  special: true
                  created_at: date
                  updated_at: date
                properties:
                  id:
                    type: string
                    example: uuid
                  title:
                    type: string
                    example: Title
                  visible:
                    type: boolean
                    example: true
                  branch_id:
                    type: string
                    example: 'Branch ID'
                  status:
                    type: string
                    example: available
                  condition:
                    type: string
                    example: good
                  special:
                    type: boolean
                    example: true
                  created_at:
                    type: string
                    example: date
                  updated_at:
                    type: string
                    example: date
      tags:
        - Admin
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: required
                  description: string
                  example: molestias
                  nullable: false
                visible:
                  type: required
                  description: boolean
                  example: saepe
                  nullable: false
                special:
                  type: required
                  description: boolean
                  example: voluptatum
                  nullable: false
                branch_id:
                  type: required
                  description: uuid
                  example: enim
                  nullable: false
                status:
                  type: required
                  description: 'string values: available,under_repair,lost'
                  example: nemo
                  nullable: false
                condition:
                  type: required
                  description: 'string values: good,worn,damaged'
                  example: aperiam
                  nullable: false
    parameters:
      -
        in: path
        name: book_id
        description: 'The ID of the book.'
        example: et
        required: true
        schema:
          type: string
  '/api/admin/bookCopies/{id}':
    get:
      summary: 'Show book copy'
      operationId: showBookCopy
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: uuid
                  title: Title
                  visible: true
                  branch_id: 'Branch ID'
                  status: available
                  condition: good
                  special: true
                  created_at: date
                  updated_at: date
                properties:
                  id:
                    type: string
                    example: uuid
                  title:
                    type: string
                    example: Title
                  visible:
                    type: boolean
                    example: true
                  branch_id:
                    type: string
                    example: 'Branch ID'
                  status:
                    type: string
                    example: available
                  condition:
                    type: string
                    example: good
                  special:
                    type: boolean
                    example: true
                  created_at:
                    type: string
                    example: date
                  updated_at:
                    type: string
                    example: date
      tags:
        - Admin
    put:
      summary: 'Update book copy'
      operationId: updateBookCopy
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - Admin
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: enim
                  nullable: false
                visible:
                  type: boolean
                  description: ''
                  example: false
                  nullable: false
                special:
                  type: boolean
                  description: ''
                  example: true
                  nullable: false
                status:
                  type: string
                  description: 'values: available,under_repair - Only when the copy is not reserved'
                  example: iste
                  nullable: false
                condition:
                  type: string
                  description: 'values: good,worn,damaged - Only when the copy is not reserved'
                  example: porro
                  nullable: false
                branch_id:
                  type: uuid
                  description: '- Only when the copy is not reserved'
                  example: in
                  nullable: false
    delete:
      summary: 'Destroy book copy'
      operationId: destroyBookCopy
      description: ''
      parameters: []
      responses:
        204:
          description: ''
      tags:
        - Admin
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the bookCopy.'
        example: qui
        required: true
        schema:
          type: string
  /api/admin/books:
    get:
      summary: 'All books'
      operationId: allBooks
      description: ''
      parameters:
        -
          in: query
          name: q
          description: ''
          example: dolores
          required: false
          schema:
            type: string
            description: ''
            example: dolores
            nullable: false
        -
          in: query
          name: page
          description: ''
          example: 18
          required: false
          schema:
            type: integer
            description: ''
            example: 18
            nullable: false
        -
          in: query
          name: per_page
          description: ''
          example: 11
          required: false
          schema:
            type: integer
            description: ''
            example: 11
            nullable: false
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: uuid
                      title: Title
                      description: null
                      visible: true
                      available: true
                      created_at: date
                  meta:
                    current_page: 1
                    last_page: 1
                    per_page: 10
                    total: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: uuid
                        title: Title
                        description: null
                        visible: true
                        available: true
                        created_at: date
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: uuid
                        title:
                          type: string
                          example: Title
                        description:
                          type: string
                          example: null
                        visible:
                          type: boolean
                          example: true
                        available:
                          type: boolean
                          example: true
                        created_at:
                          type: string
                          example: date
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 1
                      per_page:
                        type: integer
                        example: 10
                      total:
                        type: integer
                        example: 2
      tags:
        - Admin
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                q:
                  type: string
                  description: ''
                  example: est
                  nullable: true
                per_page:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 3
                  nullable: true
                page:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 24
                  nullable: true
    post:
      summary: Store
      operationId: store
      description: ''
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: uuid
                  title: Title
                  description: null
                  visible: true
                  available: true
                  created_at: date
                  updated_at: date
                properties:
                  id:
                    type: string
                    example: uuid
                  title:
                    type: string
                    example: Title
                  description:
                    type: string
                    example: null
                  visible:
                    type: boolean
                    example: true
                  available:
                    type: boolean
                    example: true
                  created_at:
                    type: string
                    example: date
                  updated_at:
                    type: string
                    example: date
      tags:
        - Admin
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: required
                  description: string
                  example: voluptas
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Vitae aut porro fuga nihil voluptas molestias quia ea.'
                  nullable: true
                visible:
                  type: required
                  description: boolean
                  example: fugit
                  nullable: false
  '/api/admin/books/{id}':
    get:
      summary: Show
      operationId: show
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: uuid
                  title: Title
                  description: null
                  visible: true
                  available: true
                  created_at: date
                  updated_at: date
                properties:
                  id:
                    type: string
                    example: uuid
                  title:
                    type: string
                    example: Title
                  description:
                    type: string
                    example: null
                  visible:
                    type: boolean
                    example: true
                  available:
                    type: boolean
                    example: true
                  created_at:
                    type: string
                    example: date
                  updated_at:
                    type: string
                    example: date
      tags:
        - Admin
    put:
      summary: Update
      operationId: update
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - Admin
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: est
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Sed odio sed maxime vel.'
                  nullable: true
                visible:
                  type: boolean
                  description: ''
                  example: true
                  nullable: false
    delete:
      summary: Destroy
      operationId: destroy
      description: ''
      parameters: []
      responses:
        204:
          description: ''
      tags:
        - Admin
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the book.'
        example: sequi
        required: true
        schema:
          type: string
  /api/admin/branches:
    get:
      summary: 'All branches'
      operationId: allBranches
      description: ''
      parameters:
        -
          in: query
          name: q
          description: ''
          example: odio
          required: false
          schema:
            type: string
            description: ''
            example: odio
            nullable: false
        -
          in: query
          name: page
          description: ''
          example: 11
          required: false
          schema:
            type: integer
            description: ''
            example: 11
            nullable: false
        -
          in: query
          name: per_page
          description: ''
          example: 3
          required: false
          schema:
            type: integer
            description: ''
            example: 3
            nullable: false
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: uuid
                      title: Title
                      address: null
                      visible: true
                      created_at: date
                  meta:
                    current_page: 1
                    last_page: 1
                    per_page: 10
                    total: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: uuid
                        title: Title
                        address: null
                        visible: true
                        created_at: date
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: uuid
                        title:
                          type: string
                          example: Title
                        address:
                          type: string
                          example: null
                        visible:
                          type: boolean
                          example: true
                        created_at:
                          type: string
                          example: date
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 1
                      per_page:
                        type: integer
                        example: 10
                      total:
                        type: integer
                        example: 2
      tags:
        - Admin
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                q:
                  type: string
                  description: ''
                  example: occaecati
                  nullable: true
                per_page:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 48
                  nullable: true
                page:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 43
                  nullable: true
    post:
      summary: Store
      operationId: store
      description: ''
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: uuid
                  title: Title
                  address: null
                  visible: true
                  created_at: date
                  updated_at: date
                properties:
                  id:
                    type: string
                    example: uuid
                  title:
                    type: string
                    example: Title
                  address:
                    type: string
                    example: null
                  visible:
                    type: boolean
                    example: true
                  created_at:
                    type: string
                    example: date
                  updated_at:
                    type: string
                    example: date
      tags:
        - Admin
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: required
                  description: string
                  example: magnam
                  nullable: false
                address:
                  type: string
                  description: ''
                  example: nemo
                  nullable: true
                visible:
                  type: required
                  description: boolean
                  example: molestiae
                  nullable: false
  '/api/admin/branches/{id}':
    get:
      summary: Show
      operationId: show
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: uuid
                  title: Title
                  address: null
                  visible: true
                  created_at: date
                  updated_at: date
                properties:
                  id:
                    type: string
                    example: uuid
                  title:
                    type: string
                    example: Title
                  address:
                    type: string
                    example: null
                  visible:
                    type: boolean
                    example: true
                  created_at:
                    type: string
                    example: date
                  updated_at:
                    type: string
                    example: date
      tags:
        - Admin
    put:
      summary: Update
      operationId: update
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - Admin
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: qui
                  nullable: false
                address:
                  type: string
                  description: ''
                  example: eveniet
                  nullable: true
                visible:
                  type: boolean
                  description: ''
                  example: true
                  nullable: false
    delete:
      summary: Destroy
      operationId: destroy
      description: ''
      parameters: []
      responses:
        204:
          description: ''
      tags:
        - Admin
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the branch.'
        example: et
        required: true
        schema:
          type: string
  '/api/admin/reservations/{reservation_id}/complete':
    post:
      summary: Complete
      operationId: complete
      description: "Confirm that the user returned the book\n\nOnly when reservation status = active"
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - Admin
    parameters:
      -
        in: path
        name: reservation_id
        description: 'The ID of the reservation.'
        example: rem
        required: true
        schema:
          type: string
  /api/admin/reservations:
    get:
      summary: 'All reservations'
      operationId: allReservations
      description: ''
      parameters:
        -
          in: query
          name: page
          description: ''
          example: 17
          required: false
          schema:
            type: integer
            description: ''
            example: 17
            nullable: false
        -
          in: query
          name: per_page
          description: ''
          example: 14
          required: false
          schema:
            type: integer
            description: ''
            example: 14
            nullable: false
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: uuid
                      user:
                        id: uuid
                        name: 'User name'
                      book:
                        id: uuid
                        title: Title
                      copy:
                        id: uuid
                        title: Title
                      branch:
                        id: uuid
                        title: Title
                        address: Address
                      days_reserved: 5
                      status: active
                      started_at: date
                      finished_at: date
                      expiration_date: date
                      created_at: date
                      updated_at: date
                  meta:
                    current_page: 1
                    last_page: 1
                    per_page: 10
                    total: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: uuid
                        user:
                          id: uuid
                          name: 'User name'
                        book:
                          id: uuid
                          title: Title
                        copy:
                          id: uuid
                          title: Title
                        branch:
                          id: uuid
                          title: Title
                          address: Address
                        days_reserved: 5
                        status: active
                        started_at: date
                        finished_at: date
                        expiration_date: date
                        created_at: date
                        updated_at: date
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: uuid
                        user:
                          type: object
                          properties:
                            id:
                              type: string
                              example: uuid
                            name:
                              type: string
                              example: 'User name'
                        book:
                          type: object
                          properties:
                            id:
                              type: string
                              example: uuid
                            title:
                              type: string
                              example: Title
                        copy:
                          type: object
                          properties:
                            id:
                              type: string
                              example: uuid
                            title:
                              type: string
                              example: Title
                        branch:
                          type: object
                          properties:
                            id:
                              type: string
                              example: uuid
                            title:
                              type: string
                              example: Title
                            address:
                              type: string
                              example: Address
                        days_reserved:
                          type: integer
                          example: 5
                        status:
                          type: string
                          example: active
                        started_at:
                          type: string
                          example: date
                        finished_at:
                          type: string
                          example: date
                        expiration_date:
                          type: string
                          example: date
                        created_at:
                          type: string
                          example: date
                        updated_at:
                          type: string
                          example: date
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 1
                      per_page:
                        type: integer
                        example: 10
                      total:
                        type: integer
                        example: 2
      tags:
        - Admin
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                q:
                  type: string
                  description: ''
                  example: nobis
                  nullable: true
                per_page:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 53
                  nullable: true
                page:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 42
                  nullable: true
  '/api/admin/reservations/{id}':
    get:
      summary: Show
      operationId: show
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: uuid
                  user:
                    id: uuid
                    name: 'User name'
                  book:
                    id: uuid
                    title: Title
                  copy:
                    id: uuid
                    title: Title
                  branch:
                    id: uuid
                    title: Title
                    address: Address
                  days_reserved: 5
                  status: active
                  started_at: date
                  finished_at: date
                  expiration_date: date
                  created_at: date
                  updated_at: date
                properties:
                  id:
                    type: string
                    example: uuid
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        example: uuid
                      name:
                        type: string
                        example: 'User name'
                  book:
                    type: object
                    properties:
                      id:
                        type: string
                        example: uuid
                      title:
                        type: string
                        example: Title
                  copy:
                    type: object
                    properties:
                      id:
                        type: string
                        example: uuid
                      title:
                        type: string
                        example: Title
                  branch:
                    type: object
                    properties:
                      id:
                        type: string
                        example: uuid
                      title:
                        type: string
                        example: Title
                      address:
                        type: string
                        example: Address
                  days_reserved:
                    type: integer
                    example: 5
                  status:
                    type: string
                    example: active
                  started_at:
                    type: string
                    example: date
                  finished_at:
                    type: string
                    example: date
                  expiration_date:
                    type: string
                    example: date
                  created_at:
                    type: string
                    example: date
                  updated_at:
                    type: string
                    example: date
      tags:
        - Admin
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the reservation.'
        example: ea
        required: true
        schema:
          type: string
  /api/auth/login:
    post:
      summary: Login
      operationId: login
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  token_type: Bearer
                  access_token: 'Access token'
                  user:
                    email: user@email.com
                    name: 'User name'
                properties:
                  token_type:
                    type: string
                    example: Bearer
                  access_token:
                    type: string
                    example: 'Access token'
                  user:
                    type: object
                    properties:
                      email:
                        type: string
                        example: user@email.com
                      name:
                        type: string
                        example: 'User name'
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: katlyn.olson@example.com
                  nullable: false
                password:
                  type: string
                  description: 'minimum character length is 6'
                  example: '"Yyo4%yQ>^o"oMI=%}|'
                  nullable: false
              required:
                - email
                - password
      security: []
  /api/auth/register:
    post:
      summary: Register
      operationId: register
      description: ''
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  token_type: Bearer
                  access_token: 'Access token'
                  user:
                    email: user@email.com
                    name: 'User name'
                properties:
                  token_type:
                    type: string
                    example: Bearer
                  access_token:
                    type: string
                    example: 'Access token'
                  user:
                    type: object
                    properties:
                      email:
                        type: string
                        example: user@email.com
                      name:
                        type: string
                        example: 'User name'
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: quisquam
                  nullable: false
                email:
                  type: string
                  description: ''
                  example: btreutel@example.net
                  nullable: false
                password:
                  type: string
                  description: ''
                  example: "tJ'YhkBoJSo"
                  nullable: false
                password_confirmation:
                  type: string
                  description: ''
                  example: quasi
                  nullable: false
              required:
                - name
                - email
                - password
                - password_confirmation
      security: []
  /api/auth/logout:
    post:
      summary: Logout
      operationId: logout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
  /api/user/books:
    get:
      summary: 'All books'
      operationId: allBooks
      description: ''
      parameters:
        -
          in: query
          name: q
          description: ''
          example: quod
          required: false
          schema:
            type: string
            description: ''
            example: quod
            nullable: false
        -
          in: query
          name: page
          description: ''
          example: 20
          required: false
          schema:
            type: integer
            description: ''
            example: 20
            nullable: false
        -
          in: query
          name: per_page
          description: ''
          example: 19
          required: false
          schema:
            type: integer
            description: ''
            example: 19
            nullable: false
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: uuid
                      title: Title
                      description: null
                      created_at: date
                  meta:
                    current_page: 1
                    last_page: 1
                    per_page: 10
                    total: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: uuid
                        title: Title
                        description: null
                        created_at: date
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: uuid
                        title:
                          type: string
                          example: Title
                        description:
                          type: string
                          example: null
                        created_at:
                          type: string
                          example: date
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 1
                      per_page:
                        type: integer
                        example: 10
                      total:
                        type: integer
                        example: 2
      tags:
        - User
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                q:
                  type: string
                  description: ''
                  example: repellat
                  nullable: true
                per_page:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 60
                  nullable: true
                page:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 42
                  nullable: true
  '/api/user/books/{id}':
    get:
      summary: 'Get book information'
      operationId: getBookInformation
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: uuid
                  title: Title
                  description: Description
                  available: true
                  copies:
                    -
                      id: uuid
                      title: Title
                      status: available
                      special: false
                      branch:
                        id: uuid
                        title: Title
                        address: Address
                properties:
                  id:
                    type: string
                    example: uuid
                  title:
                    type: string
                    example: Title
                  description:
                    type: string
                    example: Description
                  available:
                    type: boolean
                    example: true
                  copies:
                    type: array
                    example:
                      -
                        id: uuid
                        title: Title
                        status: available
                        special: false
                        branch:
                          id: uuid
                          title: Title
                          address: Address
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: uuid
                        title:
                          type: string
                          example: Title
                        status:
                          type: string
                          example: available
                        special:
                          type: boolean
                          example: false
                        branch:
                          type: object
                          properties:
                            id:
                              type: string
                              example: uuid
                            title:
                              type: string
                              example: Title
                            address:
                              type: string
                              example: Address
      tags:
        - User
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the book.'
        example: est
        required: true
        schema:
          type: string
  '/api/user/reservations/{reservation_id}/cancel':
    post:
      summary: Cancel
      operationId: cancel
      description: 'Only when reservation status = pending'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - User
    parameters:
      -
        in: path
        name: reservation_id
        description: 'The ID of the reservation.'
        example: laboriosam
        required: true
        schema:
          type: string
  /api/user/reservations:
    get:
      summary: 'All reservations'
      operationId: allReservations
      description: ''
      parameters:
        -
          in: query
          name: page
          description: ''
          example: 11
          required: false
          schema:
            type: integer
            description: ''
            example: 11
            nullable: false
        -
          in: query
          name: per_page
          description: ''
          example: 1
          required: false
          schema:
            type: integer
            description: ''
            example: 1
            nullable: false
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: uuid
                      user:
                        id: uuid
                        name: 'User name'
                      book:
                        id: uuid
                        title: Title
                      copy:
                        id: uuid
                        title: Title
                      branch:
                        id: uuid
                        title: Title
                        address: Address
                      days_reserved: 5
                      status: active
                      started_at: date
                      finished_at: date
                      expiration_date: date
                      created_at: date
                      updated_at: date
                  meta:
                    current_page: 1
                    last_page: 1
                    per_page: 10
                    total: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: uuid
                        user:
                          id: uuid
                          name: 'User name'
                        book:
                          id: uuid
                          title: Title
                        copy:
                          id: uuid
                          title: Title
                        branch:
                          id: uuid
                          title: Title
                          address: Address
                        days_reserved: 5
                        status: active
                        started_at: date
                        finished_at: date
                        expiration_date: date
                        created_at: date
                        updated_at: date
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: uuid
                        user:
                          type: object
                          properties:
                            id:
                              type: string
                              example: uuid
                            name:
                              type: string
                              example: 'User name'
                        book:
                          type: object
                          properties:
                            id:
                              type: string
                              example: uuid
                            title:
                              type: string
                              example: Title
                        copy:
                          type: object
                          properties:
                            id:
                              type: string
                              example: uuid
                            title:
                              type: string
                              example: Title
                        branch:
                          type: object
                          properties:
                            id:
                              type: string
                              example: uuid
                            title:
                              type: string
                              example: Title
                            address:
                              type: string
                              example: Address
                        days_reserved:
                          type: integer
                          example: 5
                        status:
                          type: string
                          example: active
                        started_at:
                          type: string
                          example: date
                        finished_at:
                          type: string
                          example: date
                        expiration_date:
                          type: string
                          example: date
                        created_at:
                          type: string
                          example: date
                        updated_at:
                          type: string
                          example: date
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 1
                      per_page:
                        type: integer
                        example: 10
                      total:
                        type: integer
                        example: 2
      tags:
        - User
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                q:
                  type: string
                  description: ''
                  example: sed
                  nullable: true
                per_page:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 27
                  nullable: true
                page:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 64
                  nullable: true
  '/api/user/reservations/{id}':
    get:
      summary: Show
      operationId: show
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: uuid
                  user:
                    id: uuid
                    name: 'User name'
                  book:
                    id: uuid
                    title: Title
                  copy:
                    id: uuid
                    title: Title
                  branch:
                    id: uuid
                    title: Title
                    address: Address
                  days_reserved: 5
                  status: active
                  started_at: date
                  finished_at: date
                  expiration_date: date
                  created_at: date
                  updated_at: date
                properties:
                  id:
                    type: string
                    example: uuid
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        example: uuid
                      name:
                        type: string
                        example: 'User name'
                  book:
                    type: object
                    properties:
                      id:
                        type: string
                        example: uuid
                      title:
                        type: string
                        example: Title
                  copy:
                    type: object
                    properties:
                      id:
                        type: string
                        example: uuid
                      title:
                        type: string
                        example: Title
                  branch:
                    type: object
                    properties:
                      id:
                        type: string
                        example: uuid
                      title:
                        type: string
                        example: Title
                      address:
                        type: string
                        example: Address
                  days_reserved:
                    type: integer
                    example: 5
                  status:
                    type: string
                    example: active
                  started_at:
                    type: string
                    example: date
                  finished_at:
                    type: string
                    example: date
                  expiration_date:
                    type: string
                    example: date
                  created_at:
                    type: string
                    example: date
                  updated_at:
                    type: string
                    example: date
      tags:
        - User
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the reservation.'
        example: laudantium
        required: true
        schema:
          type: string
